# Generated by Django 3.1.3 on 2021-07-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20210719_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
